const mockArticles = [
  {
    aasm_state: 'published',
    author_name: 'Tamizhvendan S',
    author_username: 'tamizhvendan',
    categories: ['JavaScript', 'webpack', 'babel', 'reactjs'],
    0: 'JavaScript',
    1: 'webpack',
    2: 'babel',
    3: 'reactjs',
    content: 'Facebook has really changed the way we think abou',
    created_at: 1450105799,
    id: 801,
    objectID: '801',
    published_at: 1450240245,
    random_key: 'du107r9zr',
    spam: false,
    summary:
      'In this blog post, we are going to see how to set up a React development environment without being sidetracked by the tools. Hopefully, this will help you develop a lean approach when setting up a development environment.',
    title: 'Setting Up a React.js Environment Using Npm, Babel 6 and Webpack',
    updated_at: 1484769764,
  },
  {
    aasm_state: 'published',
    author_name: 'David Sparks',
    author_username: 'davidnsparks',
    categories: ['laravel', 'laravel5.4', 'laravelsetup'],
    0: 'laravel',
    1: 'laravel5.4',
    2: 'laravelsetup',
    content:
      '## Larevel Out 5.4 Out Of the Box\nLaravel 5.0 brought about a lot of changes and each version brings in great new features. With 5.4 I set up a test server and installed a fresh copy. Following the setup instructions from Laravel I ran ```NPM RUN DEV``` and much to my dismey was presented with this:\n```\n> @ dev /Users/sherwin/apps/laravel/test_project\n> cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js\n\nsh: cross-env: command not found\n\nnpm ERR! Darwin 16.3.0\nnpm ERR! argv "/usr/local/Cellar/node/7.3.0/bin/node" "/usr/local/bin/npm" "run" "dev"\nnpm ERR! node v7.3.0\nnpm ERR! npm  v3.10.10\nnpm ERR! file sh\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno ENOENT\nnpm ERR! syscall spawn\nnpm ERR! @ dev: `cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`\nnpm ERR! spawn ENOENT\nnpm ERR! \nnpm ERR! Failed at the @ dev script \'cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js\'.\nnpm ERR! Make sure you have the latest version of node.js and npm installed.\nnpm ERR! If you do, this is most likely a problem with the  package,\nnpm ERR! not with npm itself.\nnpm ERR! Tell the author that this fails on your system:\nnpm ERR!     cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js\n```\n\n\n### The FIX- \nAfter a lot of googling and trouble shooting the problem appears to be in the package.json file. Although there are several ways to correct the problem this is by far the easist. Out of the box package.json looks like this:\n```\n{\n  "private": true,\n  "scripts": {\n    "dev": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",\n    "watch": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",\n    "hot": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",\n    "production": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"\n  },\n  "devDependencies": {\n    "axios": "^0.15.2",\n    "bootstrap-sass": "^3.3.7",\n    "jquery": "^3.1.0",\n    "laravel-mix": "^0.6.0",\n    "lodash": "^4.16.2",\n    "vue": "^2.0.1"\n  }\n}\n\n```\n**THE CORRECTION IS:**\n```\n{\n  "private": true,\n  "scripts": {\n    "dev": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",\n    "watch": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",\n    "hot": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",\n    "production": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"\n  },\n  "devDependencies": {\n    "axios": "^0.15.2",\n    "bootstrap-sass": "^3.3.7",\n    "jquery": "^3.1.0",\n    "laravel-mix": "^0.6.0",\n    "lodash": "^4.16.2",\n    "vue": "^2.0.1"\n  },\n  "babel": {\n    "presets": [\n      "es2015"\n    ]\n  }\n}\n\n```\n\n\n### Laravel\'s Future\nLaravel is an amazing framework built for speed and security and with the inclusion of support for vue.js right of out the box it has a bright future. I hope as the framework grows and evoloves that better solutions for upgrading between versions is implemented and that beta testing is done a bit more throughly before a version release.  \n\nIf you haven\'t checkeed out Laravel I encourge you head over to  [https://laravel.com/](https://laravel.com/)!\n\nIf you find this article useful and it saves you some headache give it a boost!\n\nHappy Coding- \n\nDavid',
    created_at: 1486910143,
    id: 1624,
    objectID: '1624',
    published_at: 1486911314,
    random_key: '57uvoofj5',
    spam: false,
    summary:
      'Laravel 5.4 Installation Error crashing at webpack.config.js. The error is in the package.json file and can be fixed by adding  "babel": {\n    "presets": [\n      "es2015"\n    ]',
    title: 'Laravel 5.4 Setup Issues',
    updated_at: 1486940979,
  },
  {
    aasm_state: 'published',
    author_name: 'Chris Harrington',
    author_username: 'chrisharrington',
    categories: ['JavaScript', 'calendar', 'webpack', 'reactjs'],
    0: 'JavaScript',
    1: 'calendar',
    2: 'webpack',
    3: 'reactjs',
    content: "I've recently been a pretty big fan of React JS a.....",
    created_at: 1441376283,
    id: 675,
    objectID: '675',
    published_at: 1441621179,
    random_key: 'du107v566',
    spam: false,
    summary:
      'I’ve recently been a pretty big fan of React JS and have been building most of my newer projects using it in combination with LESS and Webpack (both of which are awesome, although I hear the former is a little out of fashion in lieu of SCSS these days). Today, I’m going to be writing about how to create a date picker using React. I’ve made the...',
    title: 'Building a Date Picker with React JS',
    updated_at: 1484769766,
  },
]

export default mockArticles
